apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-stream-consumer
  name: redis-stream-consumer
  namespace: redis-ha
spec:
  clusterIP: None
  ports:
  - name: redis-stream-consumer
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: redis-stream-consumer
  sessionAffinity: None
  type: ClusterIP
